# This is a config for E2B sandbox template.
# You can use template ID (nglg8e8t7wtjo000co1y) or template name (vibe-nextjs-test-rajat-gangwar-141) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-rajat-gangwar-141") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-rajat-gangwar-141") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-rajat-gangwar-141')

team_id = "25f5f2ec-29c9-4f23-87c4-18d5e4da1cd1"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-rajat-gangwar-141"
template_id = "nglg8e8t7wtjo000co1y"
